version: "3"

services:
    sample_mysql:
        build:
            context: .
            dockerfile: environment/local/Dockerfile.mysql
        image: sample_mysql
        command: mysqld --character-set-server=utf8mb4 --character-set-filesystem=utf8mb4
        ports:
          - "13306:3306"
        volumes:
          - sample_mysql:/var/lib/mysql
        environment:
          MYSQL_DATABASE: sample 
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: sample
          MYSQL_PASSWORD: sample 
        networks:
          - sample 

volumes:
    sample_mysql:
networks:
    sample:
